import { ReactNode } from "react";
import { Lato } from "next/font/google";
import { StitchesRegistry } from "@/libs/stitches/registry";

import { getCssText, globalStyles } from "@/../stitches.config";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700", "900"] });

export const metadata = {
  title: "BookWise",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  globalStyles();

  return (
    <html lang="pt-BR">
      <head>
        <style
          id="stitches"
          dangerouslySetInnerHTML={{ __html: getCssText() }}
        />
      </head>
      <body className={lato.className}>
        <StitchesRegistry>
          {children}
        </StitchesRegistry>
      </body>
    </html>
  );
}
